### ISSUE TITLE
Remove Dependency On Compilation

### ISSUE THREAD

**Issue by braidn** [codeforgso/standards#2]
Doesn't GH pages have the ability to serve markdown powered pages? Why are we requiring contributors to this to understand Harp... or NPM... or Node? Seems like the compilation step isn't needed.

**Comment by jdcauley** [comment]
I agree, I already had this mostly ready from previous work and it is only mean to help frame the initial conversation rather than set the rules for contribution. My thought is to move to either straight markdown or use a jekyll site.

**Comment by braidn** [comment]
:+1: to no compilation
